# -*- coding: utf-8 -*-
"""azure_deploy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCRYiKlC1gB-BlYZInmm3H5PXApOxVf7

MILESTONE 1
"""

import pandas as pd
import numpy as np
from datetime import timedelta

np.random.seed(42)

# 2 Years Monthly Data
date_range = pd.date_range(start="2023-01-01",
                           end="2024-12-01",
                           freq="MS")

regions = ["US-East", "EU-Central"]
service_types = ["Compute", "Storage"]

azure_data = []

for date in date_range:
    month = date.month

    for region in regions:
        for service in service_types:

            #Varying Time
            random_time = timedelta(
                hours=np.random.randint(0, 24),
                minutes=np.random.randint(0, 60),
                seconds=np.random.randint(0, 60)
            )

            full_timestamp = date + random_time

            # Seasonal effect
            seasonal_factor = 1.3 if month in [6,7,8,11,12] else 1.0

            base_usage = 5000 if service == "Compute" else 3000
            usage_units = base_usage * seasonal_factor * np.random.uniform(0.85, 1.15)

            provisioned_capacity = usage_units * np.random.uniform(1.1, 1.35)

            cost_rate = 0.12 if service == "Compute" else 0.05
            cost_usd = usage_units * cost_rate

            azure_data.append([

                full_timestamp,
                region,
                service,
                round(usage_units, 2),
                round(provisioned_capacity, 2),
                round(cost_usd, 2)
            ])

azure_df = pd.DataFrame(azure_data, columns=[
    "time_stamp",
    "region",
    "service_type",
    "usage_units",
    "provisioned_capacity",
    "cost_usd"
])

print("Azure Dataset Shape:", azure_df.shape)
azure_df.head()

external_data = []

for index, row in azure_df.iterrows():

    market_demand_index = np.random.uniform(75, 120)
    customer_growth = np.random.uniform(2, 10)
    regional_growth = np.random.uniform(2.5, 6.5)

    external_data.append([
        row["time_stamp"],
        row["region"],
        round(market_demand_index, 2),
        round(customer_growth, 2),
        round(regional_growth, 2)
    ])

external_df = pd.DataFrame(external_data, columns=[
    "time_stamp",
    "region",
    "market_demand_index",
    "customer_growth",
    "regional_growth"
])

print("External Dataset Shape:", external_df.shape)
display(external_df.head())

df = pd.merge(
    azure_df,
    external_df,
    on=["time_stamp", "region"],
    how="left"
)

print("Merged Dataset Shape:", df.shape)
df.head()

# missing values
df.loc[df.sample(frac=0.02).index, "usage_units"] = np.nan
df.loc[df.sample(frac=0.02).index, "market_demand_index"] = np.nan

print("Missing Values Before Cleaning:")
print(df.isnull().sum())

# Sort for time-series consistency
df.sort_values(by=["region", "service_type", "time_stamp"], inplace=True)

df["usage_units"] = df.groupby(["region", "service_type"])["usage_units"].transform(lambda x: x.ffill())

# Filling market index with mean
df["market_demand_index"] = df["market_demand_index"].fillna(
    df["market_demand_index"].mean()
)

print("\nMissing Values After Cleaning:")
print(df.isnull().sum())

df["time_stamp"] = pd.to_datetime(df["time_stamp"])

numeric_cols = df.select_dtypes(include=np.number).columns
df[numeric_cols] = df[numeric_cols].astype(float)

print("\nDataset Info:")
print(df.info())

import plotly.express as px
region_usage = df.groupby(
    ["time_stamp", "region"]
)["usage_units"].sum().reset_index()

fig = px.line(
    region_usage,
    x="time_stamp",
    y="usage_units",
    color="region",
    title="Regional Usage Trends"
)

fig.show()

"""MILESTONE 2"""

# MILESTONE 2 - FEATURE ENGINEERING
# ===================================
# Sort data for time-series consistency
df = df.sort_values(by=["region", "service_type", "time_stamp"])

# Extract time components
df["year"] = df["time_stamp"].dt.year
df["month"] = df["time_stamp"].dt.month
df["quarter"] = df["time_stamp"].dt.quarter

# Capacity Utilization
df["capacity_utilization"] = df["usage_units"] / df["provisioned_capacity"]

# Cost Efficiency
df["cost_per_unit"] = df["cost_usd"] / df["usage_units"]

# Month-over-Month Usage Growth
df["usage_growth_rate"] = df.groupby(
    ["region", "service_type"]
)["usage_units"].pct_change()

# Peak Season Flag
df["is_peak_season"] = df["month"].isin([6,7,8,11,12]).astype(int)

# 3-Month Rolling Average Usage
df["rolling_3m_avg_usage"] = df.groupby(
    ["region", "service_type"]
)["usage_units"].transform(lambda x: x.rolling(3).mean())

df["usage_spike_flag"] = (
    df["usage_units"] > df["rolling_3m_avg_usage"] * 1.20
).astype(int)

df["lag_1_usage"] = df.groupby(
    ["region", "service_type"]
)["usage_units"].shift(1)

df["lag_2_usage"] = df.groupby(
    ["region", "service_type"]
)["usage_units"].shift(2)

df["external_demand_score"] = (
    df["market_demand_index"] * 0.5 +
    df["customer_growth"] * 0.3 +
    df["regional_growth"] * 0.2
)

lag_columns = ["usage_growth_rate",
               "rolling_3m_avg_usage",
               "lag_1_usage",
               "lag_2_usage"]

df[lag_columns] = df[lag_columns].bfill()

# Drop raw timestamp
df_model = df.drop(columns=["time_stamp"])

# Encode categorical variables
df_model = pd.get_dummies(
    df_model,
    columns=["region", "service_type"],
    drop_first=True
)

print("Final Model Dataset Shape:", df_model.shape)

# Define Target Variable
y = df_model["usage_units"]

# Define Feature Matrix
X = df_model.drop(columns=["usage_units"])

print("Feature Matrix Shape:", X.shape)
print("Target Shape:", y.shape)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("Scaled Feature Matrix Shape:", X_scaled.shape)
print(df)

print("\nModel Ready Dataset Shape:", df_model.shape)

print("\nModel Dataset Sample:")
display(df_model.head())

print("\nModel Dataset Info:")
print(df_model.info())

"""MILESTONE 3"""

pip install xgboost statsmodels

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from statsmodels.tsa.arima.model import ARIMA
from xgboost import XGBRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import GridSearchCV

df["time_stamp"] = pd.to_datetime(df["time_stamp"])

df["month"] = df["time_stamp"].dt.to_period("M")

df_monthly = df.groupby("month")["usage_units"].sum().reset_index()

df_monthly["month"] = df_monthly["month"].dt.to_timestamp()

df_monthly.set_index("month", inplace=True)

y = df_monthly["usage_units"]

split_index = int(len(y) * 0.8)

y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

y_train = y_train.dropna()
y_test = y_test.dropna()

arima_model = ARIMA(y_train, order=(2,1,2))

arima_model_fit = arima_model.fit()

arima_pred = arima_model_fit.forecast(steps=len(y_test))

features = [
    'capacity_utilization',
    'cost_per_unit',
    'usage_growth_rate',
    'rolling_3m_avg_usage',
    'lag_1_usage',
    'lag_2_usage',
    'external_demand_score'
]

target = "usage_units"

X = df[features]
y_ml = df[target]

split_index = int(len(df) * 0.8)

X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]

y_train_ml = y_ml.iloc[:split_index]
y_test_ml = y_ml.iloc[split_index:]

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [3,4,5],
    'learning_rate': [0.01,0.05,0.1]
}

xgb = XGBRegressor(random_state=42)

grid_search = GridSearchCV(
    estimator=xgb,
    param_grid=param_grid,
    cv=3,
    scoring='neg_mean_squared_error',
    verbose=1
)

grid_search.fit(X_train, y_train_ml)

print("Best Parameters:", grid_search.best_params_)

best_xgb = grid_search.best_estimator_

xgb_pred = best_xgb.predict(X_test)

def evaluate_model(y_true, y_pred, model_name):

    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    bias = np.mean(y_pred - y_true)

    print("\n", model_name)
    print("MAE:", round(mae,2))
    print("RMSE:", round(rmse,2))
    print("Forecast Bias:", round(bias,2))

evaluate_model(y_test, arima_pred, "ARIMA")

evaluate_model(y_test_ml, xgb_pred, "Tuned XGBoost")

plt.figure(figsize=(10,5))
plt.plot(y_test.index, y_test.values, label="Actual Demand")
plt.plot(y_test.index, arima_pred.values, label="ARIMA")
plt.plot(y_test.index, xgb_pred[:len(y_test)], label="XGBoost")

plt.legend()
plt.title("Azure Demand Forecast Comparison")
plt.xlabel("Time")
plt.ylabel("Usage Units")
plt.grid(True)
plt.show()

"""BEST MODEL"""

mae_arima = mean_absolute_error(y_test, arima_pred)
rmse_arima = np.sqrt(mean_squared_error(y_test, arima_pred))

mae_xgb = mean_absolute_error(y_test_ml, xgb_pred)
rmse_xgb = np.sqrt(mean_squared_error(y_test_ml, xgb_pred))

comparison = pd.DataFrame({
    "Model": ["ARIMA", "XGBoost"],
    "MAE": [mae_arima, mae_xgb],
    "RMSE": [rmse_arima, rmse_xgb]
})

print(comparison)

best_model = comparison.loc[comparison["RMSE"].idxmin()]

print("\nBest Model Based on RMSE:")
print(best_model)

if best_model["Model"] == "ARIMA":

    plt.figure(figsize=(10,5))

    plt.plot(y_test.index, y_test.values, label="Actual")

    plt.plot(y_test.index, arima_pred, label="ARIMA Prediction")

    plt.legend()

    plt.title("Best Model Forecast (ARIMA)")

    plt.show()

else:

    plt.figure(figsize=(10,5))

    plt.plot(y_test_ml.values, label="Actual")

    plt.plot(xgb_pred, label="XGBoost Prediction")

    plt.legend()

    plt.title("Best Model Forecast (XGBoost)")

    plt.show()

print("\nFinal Selected Model:", best_model["Model"])
print("Reason: Lowest RMSE value indicating better prediction accuracy.")

import joblib

if best_model["Model"] == "ARIMA":
    joblib.dump(arima_model_fit, "best_demand_forecast_model.pkl")

else:
    joblib.dump(best_xgb, "best_demand_forecast_model.pkl")

print("Best model saved successfully.")

import joblib

model = joblib.load("best_demand_forecast_model.pkl")
print("Model loaded successfully!")